Repository pharo-project/pharo-launcher, pull requests merged in 2018-07, with the labels that each got.

#147 issue146
  src/PharoLauncher-Core.package/PhLError.class/README.md
  src/PharoLauncher-Core.package/PhLError.class/instance/hasChildren.st
  src/PharoLauncher-Core.package/PhLError.class/instance/isError.st
  src/PharoLauncher-Core.package/PhLError.class/instance/longDescription.st
  src/PharoLauncher-Core.package/PhLError.class/instance/name.st
  src/PharoLauncher-Core.package/PhLError.class/instance/uiAlert.st
  src/PharoLauncher-Core.package/PhLError.class/properties.json
  src/PharoLauncher-Core.package/PhLTObject.trait/README.md
  src/PharoLauncher-Core.package/PhLTObject.trait/instance/children.st
  src/PharoLauncher-Core.package/PhLTObject.trait/instance/hasChildren.st
  src/PharoLauncher-Core.package/PhLTObject.trait/instance/isError.st
  src/PharoLauncher-Core.package/PhLTObject.trait/instance/isImage.st
  src/PharoLauncher-Core.package/PhLTObject.trait/instance/isTemplate.st
  src/PharoLauncher-Core.package/PhLTObject.trait/instance/isTemplateGroup.st
  src/PharoLauncher-Core.package/PhLTObject.trait/properties.json
  src/PharoLauncher-Download.package/PhLTObject.trait/properties.json
  src/PharoLauncher-Download.package/monticello.meta/categories.st
Labels: To Review

#160 Fix issue #142
  src/BaselineOfPharoLauncher.package/.filetree
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/README.md
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/class/DevelopmentSupport.st
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/class/baseConfigurationClassIfAbsent..st
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/class/ensureMetacello.st
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/class/ensureMetacelloBaseConfiguration.st
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/class/isMetacelloConfig.st
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/class/load.st
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/class/loadBleedingEdge.st
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/class/loadDevelopment.st
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/class/project.st
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/class/validate.st
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/instance/baseline..st
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/properties.json
  src/BaselineOfPharoLauncher.package/monticello.meta/categories.st
  src/BaselineOfPharoLauncher.package/monticello.meta/initializers.st
  src/BaselineOfPharoLauncher.package/monticello.meta/package
  src/BaselineOfPharoLauncher.package/properties.json
Labels: To Review

#163 issue159
  src/PharoLauncher-Core.package/PhLError.class/instance/hasChildren.st
  src/PharoLauncher-Core.package/PhLError.class/instance/isError.st
  src/PharoLauncher-Core.package/PhLError.class/properties.json
  src/PharoLauncher-Core.package/PhLObject.class/instance/children.st
  src/PharoLauncher-Core.package/PhLObject.class/instance/hasChildren.st
  src/PharoLauncher-Core.package/PhLObject.class/instance/isImage.st
  src/PharoLauncher-Core.package/PhLObject.class/instance/isTemplate.st
  src/PharoLauncher-Core.package/PhLObject.class/instance/isTemplateGroup.st
  src/PharoLauncher-Core.package/PhLObject.class/properties.json
  src/PharoLauncher-Core.package/PhLTObject.trait/README.md
  src/PharoLauncher-Core.package/PhLTObject.trait/instance/isError.st
  src/PharoLauncher-Core.package/PhLTObject.trait/properties.json
Labels: To Review

#168 readme spelling
  README.md
Labels: To Review

#167 Fix Issue #144
  Jenkinsfile
  build.sh
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/instance/baseline..st
Labels: To Review

#162 issue/151
  src/PharoLauncher-Core.package/PhLCreateImageFromTemplateCommand.class/class/icon.st
  src/PharoLauncher-Core.package/PhLDeleteImageCommand.class/class/icon.st
  src/PharoLauncher-Core.package/PhLLaunchImageCommand.class/class/icon.st
  src/PharoLauncher-Core.package/PhLOpenSettingsCommand.class/class/icon.st
  src/PharoLauncher-Core.package/PhLQuitCommand.class/class/icon.st
  src/PharoLauncher-Core.package/PhLRefreshImageRepositoryCommand.class/class/icon.st
  src/PharoLauncher-Core.package/PhLRefreshTemplateRepositoryCommand.class/class/icon.st
Labels: To Review

#180 Set pharo version
  Jenkinsfile
  build.sh
  windows/build-launcher-installer.bat
Labels: To Review

#185 Disable startup actions
  .project
  src/PharoLauncher-Core.package/PhLDirectoryBasedImageRepository.class/class/initialize.st
  src/PharoLauncher-Core.package/PhLROCheckStartup.class/class/initialize.st
  src/PharoLauncher-Core.package/PhLSettingBrowser.class/class/initialize.st
  src/PharoLauncher-Core.package/PhLSettingBrowser.class/class/launcherStartUp.st
  src/PharoLauncher-Core.package/PhLStartupManager.class/class/initialize.st
  src/PharoLauncher-Core.package/monticello.meta/categories.st
Labels: To Review

#181 [Issue #161] Remove unecessary methods from baseline
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/class/DevelopmentSupport.st
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/class/baseConfigurationClassIfAbsent..st
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/class/ensureMetacello.st
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/class/ensureMetacelloBaseConfiguration.st
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/class/isMetacelloConfig.st
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/class/load.st
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/class/loadBleedingEdge.st
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/class/loadDevelopment.st
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/class/project.st
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/class/validate.st
Labels: To Review

#191 Fix #171 + avoid calls to Smalltalk (use FileLocator instead)
  src/PharoLauncher-Core.package/PhLTreeSelection.class/instance/pathFor.on..st
  src/PharoLauncher-Core.package/PhLTreeSelection.class/instance/pathNameFor.on..st
  src/PharoLauncher-Core.package/monticello.meta/categories.st
  src/PharoLauncher-Tests-Download.package/PhLVirtualMachineTest.class/instance/testCanDetectExecutablePath.st
  src/PharoLauncher-Tests-Download.package/PhLVirtualMachineTest.class/instance/testCanDetectVMDirectory.st
Labels: To Review, ci, cleanup, enhancement

#195 issue194-usage-of-deprecated-Spec-classes
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/instance/baseline..st
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/instance/spec70..st
  src/PharoLauncher-Core.package/PhLCommand.class/class/icon.st
  src/PharoLauncher-Core.package/PhLCopyImageCommand.class/class/icon.st
  src/PharoLauncher-Core.package/PhLCopyPathname.class/class/icon.st
  src/PharoLauncher-Core.package/PhLCreateTemplateFromImageCommand.class/class/icon.st
  src/PharoLauncher-Core.package/PhLRecreateImageCommand.class/class/icon.st
  src/PharoLauncher-Core.package/PhLRenameImageCommand.class/class/icon.st
  src/PharoLauncher-Core.package/PhLShowImageInFolderCommand.class/class/icon.st
  src/PharoLauncher-Core.package/PhLShowImageInfoCommand.class/class/icon.st
  src/PharoLauncher-Core.package/monticello.meta/categories.st
  src/PharoLauncher-Spec.package/PhLCommand.extension/instance/asMenuItem.st
  src/PharoLauncher-Spec.package/PhLSearchableTitledTreeModel.class/instance/initializeWidgets.st
  src/PharoLauncher-Spec.package/PhLSearchableTitledTreeModel.class/instance/sortTreeWith..st
  src/PharoLauncher-Spec.package/PhLTitledTreeModel.class/instance/buildMenu..st
  src/PharoLauncher-Spec.package/PhLTitledTreeModel.class/instance/refresh.st
  src/PharoLauncher-Tests-SpecUI.package/.filetree
  src/PharoLauncher-Tests-SpecUI.package/PhLCommandContextTest.class/README.md
  src/PharoLauncher-Tests-SpecUI.package/PhLCommandContextTest.class/instance/newSelectionModelNamed..st
  src/PharoLauncher-Tests-SpecUI.package/PhLCommandContextTest.class/instance/testSingleTemplateNameWithBracketsTruncates.st
  src/PharoLauncher-Tests-SpecUI.package/PhLCommandContextTest.class/instance/testSingleTemplateNameWithoutBrackets.st
  src/PharoLauncher-Tests-SpecUI.package/PhLCommandContextTest.class/properties.json
  src/PharoLauncher-Tests-SpecUI.package/PhLTreeSelectionTest.class/README.md
  src/PharoLauncher-Tests-SpecUI.package/PhLTreeSelectionTest.class/instance/testPathNamesMultiSelectionPath.st
  src/PharoLauncher-Tests-SpecUI.package/PhLTreeSelectionTest.class/instance/testPathNamesMultiValuedPath.st
  src/PharoLauncher-Tests-SpecUI.package/PhLTreeSelectionTest.class/instance/testPathNamesSingleValuePath.st
  src/PharoLauncher-Tests-SpecUI.package/PhLTreeSelectionTest.class/instance/testPathesMultiSelectionPath.st
  src/PharoLauncher-Tests-SpecUI.package/PhLTreeSelectionTest.class/instance/testPathesMultiValuedPath.st
  src/PharoLauncher-Tests-SpecUI.package/PhLTreeSelectionTest.class/instance/testPathesSingleValuePath.st
  src/PharoLauncher-Tests-SpecUI.package/PhLTreeSelectionTest.class/properties.json
  src/PharoLauncher-Tests-SpecUI.package/monticello.meta/categories.st
  src/PharoLauncher-Tests-SpecUI.package/monticello.meta/initializers.st
  src/PharoLauncher-Tests-SpecUI.package/monticello.meta/package
  src/PharoLauncher-Tests-SpecUI.package/properties.json
Labels: To Review

#197 issue196-remove dependency on Json
  src/BaselineOfPharoLauncher.package/BaselineOfPharoLauncher.class/instance/baseline..st
  src/PharoLauncher-Core.package/PhLDownloadedTemplateGroup.class/instance/dictionary.st
  src/PharoLauncher-Core.package/PhLDownloadedTemplateGroup.class/instance/saveToFile..st
  src/PharoLauncher-Core.package/PhLJenkins2Entity.class/instance/jsonQuery..st
  src/PharoLauncher-Core.package/PhLJenkins2Entity.class/instance/query..st
  src/PharoLauncher-Core.package/monticello.meta/categories.st
Labels: To Review

#188 Add timeout on build + begin to fix install on windows
  Jenkinsfile
  windows/build-launcher-installer.bat
Labels: To Review, ci, windows

#206 [Issue #205] Move PharoLauncher to Tools in the WorldMenu
  src/PharoLauncher-Spec.package/PharoLauncher.class/class/menuCommandOn..st
Labels: To Review

#199 issue/176
  src/PharoLauncher-Core.package/PhLImage.class/instance/cleanLDLibraryPath.st
Labels: To Review

#224 [Issue #223] Add title to new Pharo Launcher
  src/PharoLauncher-IceTray.package/PhLPharoLauncher.class/class/title.st
Labels: To Review

#222 [Issue #221] Add labels to the new UI to be more user friendly
  src/PharoLauncher-IceTray.package/PhLPharoLauncher.class/instance/initializeToolbar.st
Labels: To Review

#227 [Issue #226] Improve management of the last modified date
  src/PharoLauncher-Core.package/PhLImage.class/class/settingsOn..st
  src/PharoLauncher-Core.package/PhLImage.class/instance/description.st
  src/PharoLauncher-Core.package/PhLImage.class/instance/summaryInfo.st
  src/PharoLauncher-Spec.package/Duration.extension/instance/simpleTime.ago..st
  src/PharoLauncher-Spec.package/Duration.extension/instance/simpleTimeAgo.st
  src/PharoLauncher-Spec.package/Duration.extension/properties.json
  src/PharoLauncher-Spec.package/PhLAbstractDateDisplayStrategy.class/README.md
  src/PharoLauncher-Spec.package/PhLAbstractDateDisplayStrategy.class/class/allStrategies.st
  src/PharoLauncher-Spec.package/PhLAbstractDateDisplayStrategy.class/class/allStrategiesWithNames.st
  src/PharoLauncher-Spec.package/PhLAbstractDateDisplayStrategy.class/class/displayStringOf..st
  src/PharoLauncher-Spec.package/PhLAbstractDateDisplayStrategy.class/class/isAbstract.st
  src/PharoLauncher-Spec.package/PhLAbstractDateDisplayStrategy.class/class/label.st
  src/PharoLauncher-Spec.package/PhLAbstractDateDisplayStrategy.class/properties.json
  src/PharoLauncher-Spec.package/PhLDateAndTimeDisplayStrategy.class/README.md
  src/PharoLauncher-Spec.package/PhLDateAndTimeDisplayStrategy.class/class/displayStringOf..st
  src/PharoLauncher-Spec.package/PhLDateAndTimeDisplayStrategy.class/class/label.st
  src/PharoLauncher-Spec.package/PhLDateAndTimeDisplayStrategy.class/properties.json
  src/PharoLauncher-Spec.package/PhLSearchableTitledTreePresenter.class/class/dateDisplayStrategy..st
  src/PharoLauncher-Spec.package/PhLSearchableTitledTreePresenter.class/class/dateDisplayStrategy.st
  src/PharoLauncher-Spec.package/PhLSearchableTitledTreePresenter.class/class/displayColorsForDates..st
  src/PharoLauncher-Spec.package/PhLSearchableTitledTreePresenter.class/class/displayColorsForDates.st
  src/PharoLauncher-Spec.package/PhLSearchableTitledTreePresenter.class/class/settingsOn..st
  src/PharoLauncher-Spec.package/PhLSearchableTitledTreePresenter.class/instance/dateDisplayStrategy.st
  src/PharoLauncher-Spec.package/PhLSearchableTitledTreePresenter.class/instance/displayColorsForDate.st
  src/PharoLauncher-Spec.package/PhLSearchableTitledTreePresenter.class/instance/initializeWidgets.st
  src/PharoLauncher-Spec.package/PhLSearchableTitledTreePresenter.class/instance/printDateOfLastModificationOf..st
  src/PharoLauncher-Spec.package/PhLSearchableTitledTreePresenter.class/properties.json
  src/PharoLauncher-Spec.package/PhLTimeUntilNowStrategy.class/README.md
  src/PharoLauncher-Spec.package/PhLTimeUntilNowStrategy.class/class/displayStringOf..st
  src/PharoLauncher-Spec.package/PhLTimeUntilNowStrategy.class/class/label.st
  src/PharoLauncher-Spec.package/PhLTimeUntilNowStrategy.class/properties.json
Labels: To Review
